project:
  type: book

book:
  title: "Accès à l’électricité et développement dans les espaces ruraux sénégalais"
  subtitle: "Le cas de l’énergie solaire dans la concession de Kolda-Vélingara-Médina Yoro Foulah (KVM)"
  author:
    - name: Mariama SARR
      orcid: 0000-0002-1205-0190
      email: mariama.sarr@univ-pau.fr
      affiliation: 
        - name: Université de Pau et des pays de l'Adour (UPPA)
          city: Pau
          state: FR
          url: https://www.univ-pau.fr
        - name: Laboratoire Transitions Energétiques et Environnementales (TREE -- UMR 6031 -- CNRS-UPPA)
          city: Pau
          state: FR
          url: https://tree.univ-pau.fr/
        - name: Université Cheikh Anta Diop de Dakar (UCAD)
          city: Dakar
          state: SN
          url: https://www.ucad.sn
  date: 2025-11-04
  date-format: "dddd DD MMMM YYYY"
  language: fr-FR
  chapters:
    - index.qmd
    - intro.qmd
    - Part1.qmd
    - Part2.qmd
    - references.qmd
  downloads: [pdf, docx]
  open-graph: true
  reader-mode: true
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  page-footer:
    background: floralwhite
  navbar:
    logo: img/UPPA_logo.png
    search: true
    pinned: false
  sidebar:
    style: "floating"
    background: floralwhite
    collapse-level: 3

bibliography: references.bib
csl: http://www.zotero.org/styles/norois

format:
  html:
    lang: fr
    mainfont: Arsenal
    theme:
      - litera
      - brand
    css: style.css
    toc: true
    toc-depth: 5
    toc-title: Sommaire
    toc-expand: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    lightbox: true
    fig-align: center
    fig-cap-location: bottom
  pdf:
    lang: fr
    top-level-division: part
    number-sections: true
    documentclass: scrbook
    documentclass-args: 
      - twoside=true
      - chapterprefix=true  # pour supprimer "Chapitre" devant les numéros
    fontsize: 12pt
    linestretch: 1.5
    mainfont: Crimson Pro
    sansfont: Carlito
    monofont: Cantarell
    papersize: a4
    geometry:
      - top=25mm
      - bottom=25mm
      - left=30mm
      - right=30mm
      - bindingoffset=6mm
    toc: true
    toc-depth: 5
    toc-title: Table des matières
    lot: true
    lof: true
    
    include-in-header: preamble.tex
    #include-before-body: title.tex
    template-partials: 
      - before-body.tex
      - toc.tex
      - after-body.tex
  docx:
    lang: fr
    toc: true
    toc-depth: 5
    toc-title: Table des matières
    notes-after-punctuation: false