project:
  type: book

book:
  title: "Accès à l’électricité et développement dans les espaces ruraux sénégalais"
  subtitle: "Le cas de l’énergie solaire dans la concession de Kolda-Vélingara-Médina Yoro Foulah (Kvm)"
  author: "Mariama Sarr"
  date: 2025-11-04
  language: fr-FR
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  open-graph: true
  reader-mode: true
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  page-footer:
    background: floralwhite
  navbar:
    logo: img/UPPA_logo.png
    search: true
    pinned: false
  sidebar:
    style: "floating"
    background: floralwhite
    collapse-level: 2

bibliography: references.bib

format:
  html:
    lang: fr
    theme:
      - cosmo
      - brand
    css: style.css
    toc: true
    toc-depth: 5
    toc-title: Sommaire
    toc-expand: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    lightbox: true
  pdf:
    lang: fr
    documentclass: scrbook
    documentclass-args: 
      - twoside=true
      - chapterprefix=true  # pour supprimer "Chapitre" devant les numéros
    fontsize: 12pt
    papersize: a4
    include-in-header: preamble.tex
    before-body: title.tex
    toc: true
    toc-depth: 5
    toc-title: Table des matières
    lot: true
    lof: true
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=3cm
      - right=3cm
  docx:
    lang: fr
    toc: true
    toc-depth: 5
    toc-title: Sommaire
    notes-after-punctuation: false



