project:
  type: book

book:
  title: "Accès à l’électricité et développement dans les espaces ruraux sénégalais"
  subtitle: "Le cas de l’énergie solaire dans la concession de Kolda-Vélingara-Médina Yoro Foulah (Kvm)"
  author: "Mariama Sarr"
  date: 2025-11-04
  language: fr-FR
  chapters:
    - index.qmd
    - intro.qmd
    - Part1.qmd
    - Part2.qmd
    - references.qmd
  downloads: [pdf, docx]
  open-graph: true
  reader-mode: true
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  page-footer:
    background: floralwhite
  navbar:
    logo: img/UPPA_logo.png
    search: true
    pinned: false
  sidebar:
    style: "floating"
    background: floralwhite
    collapse-level: 3

bibliography: references.bib

format:
  html:
    lang: fr
    theme:
      - cosmo
      - brand
    css: style.css
    toc: true
    toc-depth: 5
    toc-title: Sommaire
    toc-expand: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    lightbox: true
  pdf:
    lang: fr
    top-level-division: part
    number-sections: true
    documentclass: scrbook
    documentclass-args: 
      - twoside=true
      - chapterprefix=true  # pour supprimer "Chapitre" devant les numéros
    fontsize: 12pt
    linestretch: 1.5
    mainfont: Crimson Pro
    sansfont: Carlito
    monofont: Cantarell
    papersize: a4
    geometry:
      - top=25mm
      - bottom=25mm
      - left=30mm
      - right=30mm
      - bindingoffset=6mm
    toc: true
    toc-depth: 5
    toc-title: Table des matières
    lot: true
    lof: true
    
    include-in-header: preamble.tex
    #include-before-body: title.tex
    template-partials: 
      - before-body.tex
      - after-body.tex
  docx:
    lang: fr
    toc: true
    toc-depth: 5
    toc-title: Table des matières
    notes-after-punctuation: false



